spring:
  profiles:
    active: ${metric_collector_profile}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${jdbc_url}:${db_port}/${db_name}"
    username: ${db_user}
    password: ${db_password}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: ${db_max_pool_size}
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true

collector:
  services:
    - name: database_statistics
      threads: 2
      metrics:
        - name: admin-user-count
          type: DATABASE
          enabled: true
          query-timeout: 1
          query-max-rows: 1
          cron-tab: "*/30 * * * * ?"
          statement: admin-user-count.sql
          parameters:
            - name: usesuper
              value: true
        - name: db-connections-count
          type: DATABASE
          enabled: true
          query-timeout: 1
          query-max-rows: 1
          cron-tab: "*/10 * * * * ?"
          statement: db-connections-count.sql
    - name: database_objects
      threads: 1
      metrics:
        - name: tables-by-schema
          type: DATABASE #pg_catalog
          enabled: true
          query-timeout: 1
          query-max-rows: 1
          cron-tab: "*/20 * * * * ?"
          statement: tables-by-schema.sql
          parameters:
            - name: table_schema
              value: pg_catalog